[phases.setup]
packages = ["build-essential", "g++", "golang"]

[phases.build]
commands = [
  "g++ -o solver solver.cpp -static",
  "CGO_ENABLED=0 GOOS=linux go build -o go-server"
]

[phases.start]
commands = ["./go-server"]

[env]
PORT = "8080"